apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "82265615-ingress"
spec:
  ingressClassName: ingress-internal
  rules:
  - host: "82265615.ce-aa.kubepia.net" #sampleapp1-82265615.ce-aa.kubepia.net 
    http:
      paths:
      - path: /
        backend:
          service:
            name: "my-82265615"
            port:
              number: 8080
        pathType: Prefix